export const delivery_price = [
  {
    id: 1,
    tarif: "тариф",
    title: "Скоростной",
    img: "/plane.png",
    transport: "АВИА",
    delivery: "Срок доставки: 5-7 дней",
    price: "11 $/кг.",
  },
  {
    id: 2,
    tarif: "тариф",
    title: "оптимальный",
    img: "/plane.png",
    img2: "/train.png",
    transport: "АВИА",
    transport2: "ЖД",
    delivery: "Срок доставки: 9-11 дней",
    price: "8,5 $/кг.",
  },
  {
    id: 3,
    tarif: "тариф",
    title: "Бюджетный",
    img: "/plane.png",
    transport: "АВИА",
    delivery: "Срок доставки: 16-19 дней",
    price: "5,5 $/кг.",
  },
  {
    id: 4,
    tarif: "тариф",
    title: "экономичный",
    img: "/car.png",
    transport: "АВТО",
    delivery: "Срок доставки: 20-24 дня",
    price: "4,7 $/кг.",
  },
];
